### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by JeffLabonte** [dzaczek/Nordvpn#1]
I have tried your script. Sadly, it doesn't work for me.

I execute this command :

./importnordvpn.sh -u "EMAIL@gmail.com" -p "SECRET_PASSWORD" -g

it gives me this error :

```
/tmp/k7A3BI


Ovpn file in /tmp/k7A3BI- do not found 

```
I have also tried with an existing folder that I have previously downloaded, it gives me the same error! 

Hope it helps!

**Comment by dzaczek** [comment]
hi @JeffLabonte 
Could you provide me information about linux sys version and bash version. 
Sory for late respond but i miss you comment .
